baseURL = "http://www.wwafansq.com/"
languageCode = "ja"
title = "WWA FanSquare"
theme = "mdl_wwa"
publishDir = "docs"
hasCJKLaunguage = true

[[menu.main]]
  name = "コンテスト"
  url = "/contest/"
[[menu.main]]
  name = "薄い本正誤表"
  url = "/eratta/"