baseURL = "http://www.wwafansq.com/"
languageCode = "ja"
title = "WWA FanSquare"
theme = "mdl_wwa"
publishDir = "docs"
hasCJKLaunguage = true

[[menu.main]]
  name = "WWAを知る"
  url = "/about/"
  weight = 1
[[menu.main]]
  name = "作品"
  url = "/works/"
  weight = 2
[[menu.main]]
  name = "お知らせ"
  url = "/information/"
  weight = 3
[[menu.main]]
  name = "薄い本正誤表"
  url = "/eratta/"
  weight = 4